### ISSUE TITLE
etcd cluster driver

### ISSUE THREAD

**Issue by vtolstov** [sheepdog/sheepdog#148]
As of etcd growing and some very good products developed on top of it, i think that etcd cluster driver very useful.
C etcd api writed sometimes ago https://github.com/jdarcy/etcd-api

**Comment by mitake** [comment]
I agree with that etcd is a promising software for a cluster manager of sheepdog. However, etcd community is working on redesign of client API: https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md

I think we should care about this point when choosing a C client library of etcd.

**Comment by miurahr** [comment]
In 2016 March, CoreOs released etcd v2.3.0 which  introduces an experimental implementation of the next-generation v3 API, including a client and command line tool, providing developers early access to the future of etcd.
https://coreos.com/blog/etcd-v230.html

However, because C etc api client seems stopping its maintenance in years, we should continue to watch a development progress.

**Comment by vtolstov** [comment]
Last client that i'm try to use https://github.com/shafreeck/cetcd

**Comment by mitake** [comment]
@vtolstov as @miurahr points, etcd is working on its v3 API. The v3 API is significantly different from existing v2 API. The v3 is not REST based, it is gRPC based. I'll ask the etcd team about C (maybe it will be C++) client library of the v3 API. I think you should consider to use the newer API. The v2 API will be deprecated in the near future.

**Comment by miurahr** [comment]
https://github.com/shafreeck/cetcd/issues/41 
cetcd project has a willing to catch up v3 api.  It is good news and we are still waiting progress.

**Comment by vtolstov** [comment]
i don't think that this issue needs to be solved, as zetcd exists and can be used as replacement for zookeeper
